apiVersion: v1
kind: Pod
metadata:
  labels:
    app: my-nginx-lbl
  name: my-nginx-pod
spec: 
  containers:
    - name: my-nginx-cont
      image: nginx:1.22.1
      ports: 
        - containerPort: 80